---
title: "Bikeshare scheduler experiment"
author: "Coach Skufca"
date: "2022-12-04"
output: html_notebook
---

Purpose: We will set up a scheduled pull of bikeshare data to collect data every minute, where we will collect on 5 stations (ids  101 through 105) in DC.


## Packages

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(taskscheduleR)
```

To support the taskscheduleR, I have added Rscipts.exe to system path.

## A short test

```{r}
myscript="E:/Dropbox/Rwork/DS241/f2022/R/readbike.R"

taskscheduler_create(taskname = "mybiketask", rscript = myscript, 
 schedule = "MINUTE", starttime = "20:00", 
 schtasks_extra=" /et 08:44 /ed 12/05/2022",
 Rexe="Rscript.exe"
 )

```
## To stop

```{r}
taskscheduler_stop("mybiketask")
```


```{r}
taskscheduler_delete("mybiketask")
```


# Reading the data
```{r}
dfc=read_csv(here::here("f2022","data","likelog.csv")) %>%
  mutate(station_id=as.character(station_id),datetime=last_updated) 
```

```{r}
dfc %>% filter(station_id=="102",
               day(datetime)>"2022-12-50 07:00:00",) %>% ggplot(aes(datetime,num_bikes_available)) + geom_step()+
  theme_minimal()
```

